Release scripts
fkie-cad/entropython pull request #5
Opened 2024-08-14 12:10 UTC by jstucke

- added release scripts and dependencies
- updated metadata

2024-08-15 06:29 UTC, vobst requested changes
Looks good, just some minor nits.

2024-08-15 06:29 UTC, vobst commented on pyproject.toml
> +description = "A Python module for efficient calculation of Shannon byte entropy based on Rust"
Add a full stop?

2024-08-15 06:29 UTC, vobst commented on _build-wheels.sh
> +set -ex
While we are at it, I also tend to set `-u` (just for good practice, not going to change anything here). Helped me quite often.

2024-08-15 09:00 UTC, jstucke commented on _build-wheels.sh
> +set -ex
done.

2024-08-17 14:00 UTC, vobst approved these changes
Looks good - thanks! :)

2024-11-13 10:11 UTC, merged